### ISSUE TITLE
gulp-util is deprecated - should be migrated away from

### ISSUE THREAD

**Issue by wercool** [peteward44/gulp-directory-sync#11]
The gulp team recommends upgrading migrating away from gulp-util using the guidelines in the article below:

https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by peteward44** [comment]
Fair enough; but i stopped using Gulp years ago (and i think a lot of other people did too!). Gulp itself has had no updates for over 10 months. I just keep this project here for people who are still using it for their legacy projects, i have no interest in maintaining this
