### ISSUE TITLE
There's any way to ignore an .svn folder during sync?

### ISSUE THREAD

**Issue by miroamarillo** [peteward44/gulp-directory-sync#2]
Every time I sync it deletes my .svn folder inside my prod folder.  I'm doing 'dev' to 'prod'. dev is under git and prod is under svn. Any suggestions?

**Comment by peteward44** [comment]
I've added a new 'ignore' option to the config object, i've added an example use to the readme. Version is now 1.1.0. Thanks for the suggestion!

**Comment by miroamarillo** [comment]
Awesome!!! Thanks a lot!!
